#### Config file. Used all over the place
#### Note: the indentation guideline for yaml files is 2 spaces. Not the tab character or 4 spaces. You can set the preference used by Jupyterlab in the bottom right hand corner of the text editor.

# Change EXPERIMENT when initializing a new repo for an experiment. Three places to change this.
expNumber: cxi101586126 # Enter the full run number here, e.g. cxil1037623.
expDir: /sdf/data/lcls/ds/cxi/cxi101586126/ # Full path to the experimental directory here e.g/ /sdf/data/lcls/ds/cxi/cxil1037623/.

# This is not used anywhere. But is useful for debugging and version control.
template_version: 1.0
xrst_version: v1.0.0-beta.0

## Run specific information
data_paths:
- runs: [0, .inf]   # Add the range of runs that this path applies for. yaml parses .inf to float('inf') in python.
  path: /sdf/data/lcls/ds/cxi/cxi101586126/hdf5/smalldata/ # Add the full data path here.
# Add more data locations for specific runs if need be like this:
#  - runs: [20, 30]
#    path: /path/to/another/location/

photon_energy:
- runs: [0, .inf]
  energy: 9.666   # in keV
# Sample types
samples:
- runs: [1, 1]
  sample: 'Dark'
- runs: [2, 2]
  sample: 'Test'
- runs: [3, 4]
  sample: 'Dark'
- runs: [5, 7]
  sample: ['XRT Calib']
- runs: [8, 8]
  sample: 'Bad'
- runs: [9, 10]
  sample: 'Background'
- runs: [11, 11]
  sample: 'Ne'
- runs: [12, 12]
  sample: 'SF6'
- runs: [13, 13]
  sample: 'Background'
- runs: [14, 80]
  sample: 'DMP'
- runs: [81, .inf]
  sample: 'SF6'
# Spectrometer Calibration data
spectrometer_calibration:
- runs: [0, 30]
  coefficients: [0.00007, 9.58022]
- runs: [30, .inf]
  coefficients: [0.00007, 9.58756500000000]
# Timetool calibration data
tt_calibration:
- runs: [0, .inf]
  slope: -1.239952616448964e-15
  intercept: 5.173657364926712e-13
